apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  # To expose Flask app outside cluster
  selector:
    app: flask-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007  # Access app via Minikube IP:30007
